### ISSUE TITLE
_tcp

### ISSUE THREAD

**Issue by MikkelTb** [dingusdk/esp8266IHCSoapClient#1]
Hi.

When i compile the project i get this error:

```
C:\Arduino\libraries\IHCSoapClient\HTTPClientEx.cpp: In member function 'int HTTPClientEx::sendRequestEx(const char*, uint8_t*, size_t)':

C:\Arduino\libraries\IHCSoapClient\HTTPClientEx.cpp:47:7: error: '_tcp' was not declared in this scope

   if (_tcp->write(&payload[0], size) != size) {

       ^
```

i Found in the "ESP8266HTTPClient.h" that the "_tcp" has change to "_tcpDeprecated"
and the solver my issue.

Br Mikkel

**Comment by dingusdk** [comment]
It is because there has been changes to the eps8266/arduino library. I have not updated until not - and in version 2.5.2 it is called "_client". I have just updated with this change.
